import Drawer from "@/components/client/Drawer";
import Navbar from "@/components/client/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Idea Fusion - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" bg-red-300 flex">
          <div className=" bg-green-200 md:w-[80%] w-full h-screen">
            <Navbar />
            <div className=" bg-black max-h-[90%] overflow-scroll">
              {children}
            </div>
          </div>
          <div className="bg-blue-400 h-screen w-[20%] md:block hidden">
            <Drawer />
          </div>

          {/* <div className=" w-full bg-gray-800 h-[8%]">
            <Navbar />
            <div className=" md:hidden block">
              <Drawer />
            </div>
          </div>
          <div className=" w-full bg-blue-200 h-[92%] flex">
            <div className=" md:w-[85%] w-full bg-green-300">{children}</div>
          </div> */}
        </div>
      </body>
    </html>
  );
}
